
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-external-secret
  namespace: default
spec:
  refreshInterval: "10s" # 
  secretStoreRef:
    name: aws-secretsmanager-store
    kind: ClusterSecretStore
  target:
    name: redis-credentials # The name of the K8s Secret it will generate
    creationPolicy: Owner
  data:
  - remoteRef:
      key: prod/redis/password
      property: password
    secretKey: redis-password
